# Author: Talos Thoren
# Date: January 26, 2013
# Description: Makefile for major keys, in order of filenames

LILY=/usr/bin/lilypond --png

all: A_min.png A_flat_min.png A_sharp_min.png B_min.png B_flat_min.png\
     C_min.png C_sharp_min.png D_min.png D_sharp_min.png E_min.png\
     E_flat_min.png F_min.png F_sharp_min.png G_min.png G_sharp_min.png

A_min.png: A_min.ly
	$(LILY) A_min.ly

A_flat_min.png: A_flat_min.ly
	$(LILY) A_flat_min.ly

A_sharp_min.png: A_sharp_min.ly
	$(LILY) A_sharp_min.ly

B_min.png: B_min.ly
	$(LILY) B_min.ly

B_flat_min.png: B_flat_min.ly
	$(LILY) B_flat_min.ly

C_min.png: C_min.ly
	$(LILY) C_min.ly

C_sharp_min.png: C_sharp_min.ly
	$(LILY) C_sharp_min.ly

D_min.png: D_min.ly
	$(LILY) D_min.ly

D_sharp_min.png: D_sharp_min.ly
	$(LILY) D_sharp_min.ly

E_min.png: E_min.ly
	$(LILY) E_min.ly

E_flat_min.png: E_flat_min.ly
	$(LILY) E_flat_min.ly

F_min.png: F_min.ly
	$(LILY) F_min.ly

F_sharp_min.png: F_sharp_min.ly
	$(LILY) F_sharp_min.ly

G_min.png: G_min.ly
	$(LILY) G_min.ly

G_sharp_min.png: G_sharp_min.ly
	$(LILY) G_sharp_min.ly

