# Author: Talos Thoren
# Date: January 26, 2013
# Description: Makefile for major keys, in order of filenames

LILY=/usr/bin/lilypond --png

all: A_Maj.png A_flat_Maj.png B_Maj.png B_flat_Maj.png C_Maj.png\
     C_flat_Maj.png C_sharp_Maj.png D_Maj.png D_flat_Maj.png\
     E_Maj.png E_flat_Maj.png F_Maj.png F_sharp_Maj.png G_Maj.png\
     G_flat_Maj.png

A_Maj.png: A_Maj.ly
	$(LILY) A_Maj.ly

A_flat_Maj.png: A_flat_Maj.ly
	$(LILY) A_flat_Maj.ly

B_Maj.png: B_Maj.ly
	$(LILY) B_Maj.ly

B_flat_Maj.png: B_flat_Maj.ly
	$(LILY) B_flat_Maj.ly

C_Maj.png: C_Maj.ly
	$(LILY) C_Maj.ly

C_flat_Maj.png: C_flat_Maj.ly
	$(LILY) C_flat_Maj.ly

C_sharp_Maj.png: C_sharp_Maj.ly
	$(LILY) C_sharp_Maj.ly

D_Maj.png: D_Maj.ly
	$(LILY) D_Maj.ly

D_flat_Maj.png: D_flat_Maj.ly
	$(LILY) D_flat_Maj.ly

E_Maj.png: E_Maj.ly
	$(LILY) E_Maj.ly

E_flat_Maj.png: E_flat_Maj.ly
	$(LILY) E_flat_Maj.ly

F_Maj.png: F_Maj.ly
	$(LILY) F_Maj.ly

F_sharp_Maj.png: F_sharp_Maj.ly
	$(LILY) F_sharp_Maj.ly

G_Maj.png: G_Maj.ly
	$(LILY) G_Maj.ly

G_flat_Maj.png: G_flat_Maj.ly
	$(LILY) G_flat_Maj.ly

